language: python
python:
  - 2.7

env:
  global:
    - DJANGO_SETTINGS_MODULE=tests.test_settings
    - TIMEOUT=1000
  matrix:
    - DJANGO=1.7

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install django-cors-headers

script: python runtests.py
