language: python
python:
  - 2.7
  - 3.4

env:
  global:
    - DJANGO_SETTINGS_MODULE=tests.test_settings
    - TIMEOUT=1000
  matrix:
    - DJANGO=1.4.3
    - DJANGO=1.7

install:
  - pip install -q Django==$DJANGO --use-mirrors

script: python runtests.py

matrix:
  exclude:
    - python: 3.4
      env: DJANGO=1.4.3